Repository EXXETA/correomqtt, pull requests merged in 2021-02, with the labels that each got.

#59 Fix app icon on linux when installing from generated jpackage file
  .travis/build.bash
  .travis/resources/linux/CorreoMQTT.desktop
  src/main/java/org/correomqtt/CorreoPreloader.java
  src/main/resources/org/correomqtt/business/utils/version.txt
Labels: bug, documentation

#68 Feature/plugin for the systopic
  protocol.xml
  src/main/java/org/correomqtt/business/model/SysTopic.java
  src/main/java/org/correomqtt/gui/cell/SysTopicCell.java
  src/main/java/org/correomqtt/gui/controller/ControlBarController.java
  src/main/java/org/correomqtt/gui/controller/SysTopicViewController.java
  src/main/java/org/correomqtt/gui/model/SysTopicPropertiesDTO.java
  src/main/java/org/correomqtt/gui/transformer/SysTopicTransformer.java
  src/main/java/org/correomqtt/plugin/spi/MainToolbarHook.java
  src/main/resources/org/correomqtt/gui/cell/sysTopicCell.fxml
  src/main/resources/org/correomqtt/gui/controller/controlBarView.fxml
  src/main/resources/org/correomqtt/gui/controller/sysTopicsView.fxml
  src/main/resources/org/correomqtt/gui/css/sysTopicCell.css
  src/main/resources/org/correomqtt/gui/css/sysTopicsView.css
Labels: enhancement

#71 bug fix QoS 2
  src/main/java/org/correomqtt/business/model/Qos.java
Labels: bug
